import React from 'react';
import { Clock, Brain } from 'lucide-react';
import { PredictionChart } from '../components/Charts';
import { StatCard } from '../components/StatCard';
import { StatusBadge } from '../components/StatusBadge';
import { todayPrediction, todayStats } from '../data/mockData';

export const TodayPrediction: React.FC = () => (
  <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
    {/* Header */}
    <div>
      <div className="section-eyebrow" style={{ marginBottom: '4px' }}>LSTM Model 1</div>
      <h2 className="section-heading">Today's Radiation Prediction</h2>
      <p style={{ fontSize: '0.78rem', color: 'var(--text-secondary)', marginTop: '4px' }}>
        LSTM Model 1 — Next 24 Hours
      </p>
    </div>

    {/* Model info card */}
    <div className="glass-card" style={{ padding: '1.25rem' }}>
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: '1.5rem', alignItems: 'flex-start' }}>
        <div style={{
          width: '44px', height: '44px',
          background: 'rgba(0,200,255,0.12)',
          border: '1px solid var(--border-bright)',
          borderRadius: '12px',
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          color: 'var(--ion)', flexShrink: 0,
        }}>
          <Brain size={22} />
        </div>
        <div style={{ flex: 1 }}>
          <div style={{ fontWeight: 700, fontSize: '0.95rem', marginBottom: '0.5rem' }}>Model Information</div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.75rem', fontSize: '0.72rem' }}>
            {[
              { label: 'Model', value: 'LSTM Model 1' },
              { label: 'Architecture', value: 'Long Short-Term Memory' },
              { label: 'Input', value: 'Previous 6 timestamps' },
              { label: 'Output', value: 'Next 24 hours' },
              { label: 'Training data', value: 'Historical SEP events' },
            ].map(f => (
              <div key={f.label} style={{
                background: 'rgba(0,200,255,0.06)',
                border: '1px solid var(--border)',
                borderRadius: '6px', padding: '4px 10px',
              }}>
                <span style={{ color: 'var(--text-muted)' }}>{f.label}: </span>
                <span style={{ color: 'var(--ion)', fontFamily: "'JetBrains Mono',monospace", fontWeight: 600 }}>{f.value}</span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>

    {/* Prediction chart */}
    <div className="glass-card" style={{ padding: '1.25rem' }}>
      <div style={{ fontWeight: 700, fontSize: '0.95rem', marginBottom: '0.25rem' }}>24-Hour Radiation Forecast</div>
      <div style={{ fontSize: '0.7rem', color: 'var(--text-secondary)', marginBottom: '1rem' }}>
        Confidence band shown — actual readings will fall between upper and lower bounds with 90% probability.
      </div>
      <PredictionChart data={todayPrediction} showConfidence />
    </div>

    {/* Stats row */}
    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))', gap: '1rem' }}>
      <StatCard label="Lowest Expected" value={`${todayStats.lowest} Gy`} statusColor="safe" icon={<Clock size={14} />} />
      <StatCard label="Average" value={`${todayStats.average} Gy`} statusColor="ion" />
      <StatCard label="Peak" value={`${todayStats.peak} Gy`} statusColor="warn" />
      <div className="glass-card" style={{ padding: '1.25rem' }}>
        <div style={{ fontSize: '0.6rem', color: 'var(--text-muted)', fontFamily: "'JetBrains Mono',monospace", letterSpacing: '0.1em', marginBottom: '8px' }}>RISK LEVEL</div>
        <div style={{ marginBottom: '6px' }}><StatusBadge status={todayStats.riskLevel} size="lg" glow /></div>
        <div style={{ fontSize: '0.65rem', color: 'var(--text-secondary)' }}>24-hour risk assessment</div>
      </div>
    </div>

    {/* AI interpretation */}
    <div className="glass-card" style={{ padding: '1.25rem', borderColor: 'rgba(56,189,248,0.25)' }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '0.75rem' }}>
        <Brain size={16} color="var(--ion)" />
        <div style={{ fontSize: '0.72rem', fontWeight: 700, color: 'var(--ion)', letterSpacing: '0.08em', textTransform: 'uppercase' }}>
          AI Interpretation
        </div>
      </div>
      <p style={{ fontSize: '0.82rem', color: 'var(--text-secondary)', lineHeight: 1.7 }}>
        {todayStats.aiInterpretation}
      </p>
      <p style={{ fontSize: '0.72rem', color: 'var(--text-muted)', marginTop: '8px', lineHeight: 1.5 }}>
        This analysis is generated by the LSTM model based on recent radiation trends. It is a statistical forecast — always follow official mission safety protocols.
      </p>
    </div>
  </div>
);
